# Generated by Django 4.2.5 on 2023-09-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topkalaTemplate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
