# Generated by Django 4.2.5 on 2023-09-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topkalaTemplate', '0002_alter_category_url_alter_subcategory_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topkalaTemplate.category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
