# Generated by Django 4.2.5 on 2023-09-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topkalaTemplate', '0003_category_parent_delete_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_image_path/')),
            ],
        ),
    ]
