# Generated by Django 4.2.5 on 2023-09-16 15:04

from django.db import migrations, models
import django.db.models.deletion
import topkalaTemplate.models


class Migration(migrations.Migration):

    dependencies = [
        ('topkalaTemplate', '0005_alter_sliderimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان محصول')),
                ('image', models.ImageField(upload_to=topkalaTemplate.models.product_image_path, verbose_name='تصویر محصول')),
                ('old_price', models.IntegerField(verbose_name='قیمت قبلی')),
                ('new_price', models.IntegerField(verbose_name='قیمت جدید')),
                ('discount_percent', models.PositiveIntegerField(verbose_name='درصد تخفیف')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topkalaTemplate.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
