# Generated by Django 4.2.5 on 2023-09-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topkalaTemplate', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='countdown_date',
            field=models.DateTimeField(null=True),
        ),
    ]
