# Generated by Django 4.2.5 on 2023-09-18 09:03

from django.db import migrations, models
import topkalaTemplate.models


class Migration(migrations.Migration):

    dependencies = [
        ('topkalaTemplate', '0007_product_countdown_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام برند')),
                ('logo', models.ImageField(upload_to=topkalaTemplate.models.special_brand_image_path, verbose_name='لوگو برند')),
            ],
            options={
                'verbose_name': 'برند ویژه',
                'verbose_name_plural': 'برندهای ویژه',
            },
        ),
    ]
