# Generated by Django 4.2.5 on 2023-09-21 09:40

from django.db import migrations, models
import django.db.models.deletion
import topkalaTemplate.models


class Migration(migrations.Migration):

    dependencies = [
        ('topkalaTemplate', '0008_specialbrand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=topkalaTemplate.models.product_image_path, verbose_name='تصویر محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='topkalaTemplate.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
            },
        ),
    ]
